
#ifndef VTKPVVTKEXTENSIONSINTERACTIONSTYLE_EXPORT_H
#define VTKPVVTKEXTENSIONSINTERACTIONSTYLE_EXPORT_H

#ifdef VTKPVVTKEXTENSIONSINTERACTIONSTYLE_STATIC_DEFINE
#  define VTKPVVTKEXTENSIONSINTERACTIONSTYLE_EXPORT
#  define VTKPVVTKEXTENSIONSINTERACTIONSTYLE_NO_EXPORT
#else
#  ifndef VTKPVVTKEXTENSIONSINTERACTIONSTYLE_EXPORT
#    ifdef VTKExtensionsInteractionStyle_EXPORTS
        /* We are building this library */
#      define VTKPVVTKEXTENSIONSINTERACTIONSTYLE_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKPVVTKEXTENSIONSINTERACTIONSTYLE_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKPVVTKEXTENSIONSINTERACTIONSTYLE_NO_EXPORT
#    define VTKPVVTKEXTENSIONSINTERACTIONSTYLE_NO_EXPORT 
#  endif
#endif

#ifndef VTKPVVTKEXTENSIONSINTERACTIONSTYLE_DEPRECATED
#  define VTKPVVTKEXTENSIONSINTERACTIONSTYLE_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKPVVTKEXTENSIONSINTERACTIONSTYLE_DEPRECATED_EXPORT
#  define VTKPVVTKEXTENSIONSINTERACTIONSTYLE_DEPRECATED_EXPORT VTKPVVTKEXTENSIONSINTERACTIONSTYLE_EXPORT VTKPVVTKEXTENSIONSINTERACTIONSTYLE_DEPRECATED
#endif

#ifndef VTKPVVTKEXTENSIONSINTERACTIONSTYLE_DEPRECATED_NO_EXPORT
#  define VTKPVVTKEXTENSIONSINTERACTIONSTYLE_DEPRECATED_NO_EXPORT VTKPVVTKEXTENSIONSINTERACTIONSTYLE_NO_EXPORT VTKPVVTKEXTENSIONSINTERACTIONSTYLE_DEPRECATED
#endif

/* NOLINTNEXTLINE(readability-avoid-unconditional-preprocessor-if) */
#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKPVVTKEXTENSIONSINTERACTIONSTYLE_NO_DEPRECATED
#    define VTKPVVTKEXTENSIONSINTERACTIONSTYLE_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkPVVTKExtensionsInteractionStyleModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* VTKPVVTKEXTENSIONSINTERACTIONSTYLE_EXPORT_H */
