
#ifndef VTKPVINCUBATORCORE_EXPORT_H
#define VTKPVINCUBATORCORE_EXPORT_H

#ifdef VTKPVINCUBATORCORE_STATIC_DEFINE
#  define VTKPVINCUBATORCORE_EXPORT
#  define VTKPVINCUBATORCORE_NO_EXPORT
#else
#  ifndef VTKPVINCUBATORCORE_EXPORT
#    ifdef Core_EXPORTS
        /* We are building this library */
#      define VTKPVINCUBATORCORE_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKPVINCUBATORCORE_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKPVINCUBATORCORE_NO_EXPORT
#    define VTKPVINCUBATORCORE_NO_EXPORT 
#  endif
#endif

#ifndef VTKPVINCUBATORCORE_DEPRECATED
#  define VTKPVINCUBATORCORE_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKPVINCUBATORCORE_DEPRECATED_EXPORT
#  define VTKPVINCUBATORCORE_DEPRECATED_EXPORT VTKPVINCUBATORCORE_EXPORT VTKPVINCUBATORCORE_DEPRECATED
#endif

#ifndef VTKPVINCUBATORCORE_DEPRECATED_NO_EXPORT
#  define VTKPVINCUBATORCORE_DEPRECATED_NO_EXPORT VTKPVINCUBATORCORE_NO_EXPORT VTKPVINCUBATORCORE_DEPRECATED
#endif

/* NOLINTNEXTLINE(readability-avoid-unconditional-preprocessor-if) */
#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKPVINCUBATORCORE_NO_DEPRECATED
#    define VTKPVINCUBATORCORE_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkPVIncubatorCoreModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* VTKPVINCUBATORCORE_EXPORT_H */
