# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.29)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS BagPlotViewsAndFilters::BagPlotViewsAndFiltersBagPlot)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target BagPlotViewsAndFilters::BagPlotViewsAndFiltersBagPlot
add_library(BagPlotViewsAndFilters::BagPlotViewsAndFiltersBagPlot SHARED IMPORTED)

set_target_properties(BagPlotViewsAndFilters::BagPlotViewsAndFiltersBagPlot PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/pv/ParaView/Plugins/BagPlotViewsAndFilters/BagPlot;D:/pv/build/Plugins/BagPlotViewsAndFilters/BagPlot;D:/pv/ParaView/Plugins/BagPlotViewsAndFilters/BagPlot;D:/pv/build/Plugins/BagPlotViewsAndFilters/BagPlot;D:/pv/ParaView/Plugins/BagPlotViewsAndFilters/BagPlot;D:/pv/build/Plugins/BagPlotViewsAndFilters/BagPlot"
  INTERFACE_LINK_LIBRARIES "ParaView::RemotingViews;VTK::CommonExecutionModel"
)

if(NOT CMAKE_VERSION VERSION_LESS "3.23.0")
  target_sources(BagPlotViewsAndFilters::BagPlotViewsAndFiltersBagPlot
    INTERFACE
      FILE_SET "vtk_module_templates"
      TYPE "HEADERS"
      BASE_DIRS "D:/pv/ParaView/Plugins/BagPlotViewsAndFilters/BagPlot"
      FILES 
    INTERFACE
      FILE_SET "vtk_module_headers"
      TYPE "HEADERS"
      BASE_DIRS "D:/pv/ParaView/Plugins/BagPlotViewsAndFilters/BagPlot"
      FILES "D:/pv/ParaView/Plugins/BagPlotViewsAndFilters/BagPlot/vtkPVExtractBagPlots.h" "D:/pv/ParaView/Plugins/BagPlotViewsAndFilters/BagPlot/vtkSMFunctionalBagChartSeriesSelectionDomain.h" "D:/pv/ParaView/Plugins/BagPlotViewsAndFilters/BagPlot/vtkSMBagChartSeriesListDomain.h" "D:/pv/ParaView/Plugins/BagPlotViewsAndFilters/BagPlot/vtkPVBagChartRepresentation.h" "D:/pv/ParaView/Plugins/BagPlotViewsAndFilters/BagPlot/vtkPVBagPlotMatrixView.h" "D:/pv/ParaView/Plugins/BagPlotViewsAndFilters/BagPlot/vtkPVBagPlotMatrixRepresentation.h"
    INTERFACE
      FILE_SET "vtk_module_nowrap_headers"
      TYPE "HEADERS"
      BASE_DIRS "D:/pv/ParaView/Plugins/BagPlotViewsAndFilters/BagPlot"
      FILES "D:/pv/build/Plugins/BagPlotViewsAndFilters/BagPlot/vtkBagPlotViewsAndFiltersBagPlotModule.h"
  )
else()
  set_property(TARGET BagPlotViewsAndFilters::BagPlotViewsAndFiltersBagPlot
    APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES
      "D:/pv/ParaView/Plugins/BagPlotViewsAndFilters/BagPlot"
      "D:/pv/ParaView/Plugins/BagPlotViewsAndFilters/BagPlot"
      "D:/pv/ParaView/Plugins/BagPlotViewsAndFilters/BagPlot"
  )
endif()

# Import target "BagPlotViewsAndFilters::BagPlotViewsAndFiltersBagPlot" for configuration "Release"
set_property(TARGET BagPlotViewsAndFilters::BagPlotViewsAndFiltersBagPlot APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(BagPlotViewsAndFilters::BagPlotViewsAndFiltersBagPlot PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/pv/build/bin/paraview-5.13/plugins/BagPlotViewsAndFilters/vtkBagPlotViewsAndFiltersBagPlot.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "ParaView::VTKExtensionsFiltersRendering;ParaView::VTKExtensionsFiltersStatistics;ParaView::VTKExtensionsMisc;VTK::FiltersExtraction;VTK::FiltersStatistics;VTK::InfovisCore"
  IMPORTED_LOCATION_RELEASE "D:/pv/build/bin/paraview-5.13/plugins/BagPlotViewsAndFilters/vtkBagPlotViewsAndFiltersBagPlot.dll"
  )

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "ParaView::RemotingViews" "VTK::CommonExecutionModel" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
