# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.29)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS DigitalSignalProcessing::DSPDataModel DigitalSignalProcessing::DSPFiltersPlugin)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target DigitalSignalProcessing::DSPDataModel
add_library(DigitalSignalProcessing::DSPDataModel STATIC IMPORTED)

set_target_properties(DigitalSignalProcessing::DSPDataModel PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/pv/ParaView/Plugins/DSP/DataModel;D:/pv/build/Plugins/DSP/DataModel;D:/pv/ParaView/Plugins/DSP/DataModel;D:/pv/build/Plugins/DSP/DataModel;D:/pv/ParaView/Plugins/DSP/DataModel;D:/pv/build/Plugins/DSP/DataModel"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonExecutionModel;\$<LINK_ONLY:VTK::CommonDataModel>"
)

if(NOT CMAKE_VERSION VERSION_LESS "3.23.0")
  target_sources(DigitalSignalProcessing::DSPDataModel
    INTERFACE
      FILE_SET "vtk_module_templates"
      TYPE "HEADERS"
      BASE_DIRS "D:/pv/ParaView/Plugins/DSP/DataModel"
      FILES 
    INTERFACE
      FILE_SET "vtk_module_headers"
      TYPE "HEADERS"
      BASE_DIRS "D:/pv/ParaView/Plugins/DSP/DataModel"
      FILES 
    INTERFACE
      FILE_SET "vtk_module_nowrap_headers"
      TYPE "HEADERS"
      BASE_DIRS "D:/pv/ParaView/Plugins/DSP/DataModel"
      FILES "D:/pv/ParaView/Plugins/DSP/DataModel/vtkArrayDispatchDSPArrayList.h" "D:/pv/ParaView/Plugins/DSP/DataModel/vtkMultiDimensionalArray.h" "D:/pv/ParaView/Plugins/DSP/DataModel/vtkMultiDimensionalImplicitBackend.h" "D:/pv/build/Plugins/DSP/DataModel/vtkDSPDataModelModule.h"
  )
else()
  set_property(TARGET DigitalSignalProcessing::DSPDataModel
    APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES
      "D:/pv/ParaView/Plugins/DSP/DataModel"
      "D:/pv/ParaView/Plugins/DSP/DataModel"
      "D:/pv/ParaView/Plugins/DSP/DataModel"
  )
endif()

# Create imported target DigitalSignalProcessing::DSPFiltersPlugin
add_library(DigitalSignalProcessing::DSPFiltersPlugin STATIC IMPORTED)

set_target_properties(DigitalSignalProcessing::DSPFiltersPlugin PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/pv/ParaView/Plugins/DSP/Filters;D:/pv/build/Plugins/DSP/Filters;D:/pv/ParaView/Plugins/DSP/Filters;D:/pv/build/Plugins/DSP/Filters;D:/pv/ParaView/Plugins/DSP/Filters;D:/pv/build/Plugins/DSP/Filters"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;VTK::FiltersGeneral;\$<LINK_ONLY:DigitalSignalProcessing::DSPDataModel>;\$<LINK_ONLY:VTK::FiltersCore>;\$<LINK_ONLY:VTK::FiltersExtraction>;\$<LINK_ONLY:VTK::ParallelCore>"
)

if(NOT CMAKE_VERSION VERSION_LESS "3.23.0")
  target_sources(DigitalSignalProcessing::DSPFiltersPlugin
    INTERFACE
      FILE_SET "vtk_module_templates"
      TYPE "HEADERS"
      BASE_DIRS "D:/pv/ParaView/Plugins/DSP/Filters"
      FILES 
    INTERFACE
      FILE_SET "vtk_module_headers"
      TYPE "HEADERS"
      BASE_DIRS "D:/pv/ParaView/Plugins/DSP/Filters"
      FILES "D:/pv/ParaView/Plugins/DSP/Filters/vtkAccousticUtilities.h" "D:/pv/ParaView/Plugins/DSP/Filters/vtkBandFiltering.h" "D:/pv/ParaView/Plugins/DSP/Filters/vtkDSPTableFFT.h" "D:/pv/ParaView/Plugins/DSP/Filters/vtkMeanPowerSpectralDensity.h" "D:/pv/ParaView/Plugins/DSP/Filters/vtkMergeReduceTables.h" "D:/pv/ParaView/Plugins/DSP/Filters/vtkMultiDimensionBrowser.h" "D:/pv/ParaView/Plugins/DSP/Filters/vtkProjectSpectrumMagnitude.h" "D:/pv/ParaView/Plugins/DSP/Filters/vtkSoundQuantitiesCalculator.h" "D:/pv/ParaView/Plugins/DSP/Filters/vtkSpectrogramFilter.h" "D:/pv/ParaView/Plugins/DSP/Filters/vtkTemporalMultiplexing.h"
    INTERFACE
      FILE_SET "vtk_module_nowrap_headers"
      TYPE "HEADERS"
      BASE_DIRS "D:/pv/ParaView/Plugins/DSP/Filters"
      FILES "D:/pv/build/Plugins/DSP/Filters/vtkDSPFiltersPluginModule.h"
  )
else()
  set_property(TARGET DigitalSignalProcessing::DSPFiltersPlugin
    APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES
      "D:/pv/ParaView/Plugins/DSP/Filters"
      "D:/pv/ParaView/Plugins/DSP/Filters"
      "D:/pv/ParaView/Plugins/DSP/Filters"
  )
endif()

# Import target "DigitalSignalProcessing::DSPDataModel" for configuration "Release"
set_property(TARGET DigitalSignalProcessing::DSPDataModel APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DigitalSignalProcessing::DSPDataModel PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/pv/build/bin/paraview-5.13/plugins/DigitalSignalProcessing/vtkDSPDataModel.lib"
  )

# Import target "DigitalSignalProcessing::DSPFiltersPlugin" for configuration "Release"
set_property(TARGET DigitalSignalProcessing::DSPFiltersPlugin APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(DigitalSignalProcessing::DSPFiltersPlugin PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "D:/pv/build/bin/paraview-5.13/plugins/DigitalSignalProcessing/vtkDSPFiltersPlugin.lib"
  )

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "VTK::CommonCore" "VTK::CommonExecutionModel" "VTK::CommonDataModel" "VTK::FiltersGeneral" "VTK::FiltersCore" "VTK::FiltersExtraction" "VTK::ParallelCore" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
