# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.29)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS ParaView::pvserver ParaView::pvdataserver ParaView::pvrenderserver)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target ParaView::pvserver
add_executable(ParaView::pvserver IMPORTED)

# Create imported target ParaView::pvdataserver
add_executable(ParaView::pvdataserver IMPORTED)

# Create imported target ParaView::pvrenderserver
add_executable(ParaView::pvrenderserver IMPORTED)

# Import target "ParaView::pvserver" for configuration "Release"
set_property(TARGET ParaView::pvserver APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ParaView::pvserver PROPERTIES
  IMPORTED_LOCATION_RELEASE "D:/pv/build/bin/pvserver.exe"
  )

# Import target "ParaView::pvdataserver" for configuration "Release"
set_property(TARGET ParaView::pvdataserver APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ParaView::pvdataserver PROPERTIES
  IMPORTED_LOCATION_RELEASE "D:/pv/build/bin/pvdataserver.exe"
  )

# Import target "ParaView::pvrenderserver" for configuration "Release"
set_property(TARGET ParaView::pvrenderserver APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ParaView::pvrenderserver PROPERTIES
  IMPORTED_LOCATION_RELEASE "D:/pv/build/bin/pvrenderserver.exe"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
