# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.29)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS ParaViewIncubator::Core)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target ParaViewIncubator::Core
add_library(ParaViewIncubator::Core SHARED IMPORTED)

set_target_properties(ParaViewIncubator::Core PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/pv/ParaView/Incubator/Core;D:/pv/build/Incubator/Core;D:/pv/ParaView/Incubator/Core;D:/pv/build/Incubator/Core;D:/pv/ParaView/Incubator/Core;D:/pv/build/Incubator/Core"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore"
)

if(NOT CMAKE_VERSION VERSION_LESS "3.23.0")
  target_sources(ParaViewIncubator::Core
    INTERFACE
      FILE_SET "vtk_module_templates"
      TYPE "HEADERS"
      BASE_DIRS "D:/pv/ParaView/Incubator/Core"
      FILES 
    INTERFACE
      FILE_SET "vtk_module_headers"
      TYPE "HEADERS"
      BASE_DIRS "D:/pv/ParaView/Incubator/Core"
      FILES "D:/pv/ParaView/Incubator/Core/vtkPVIncubator.h"
    INTERFACE
      FILE_SET "vtk_module_nowrap_headers"
      TYPE "HEADERS"
      BASE_DIRS "D:/pv/ParaView/Incubator/Core"
      FILES "D:/pv/build/Incubator/Core/vtkPVIncubatorCoreModule.h"
  )
else()
  set_property(TARGET ParaViewIncubator::Core
    APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES
      "D:/pv/ParaView/Incubator/Core"
      "D:/pv/ParaView/Incubator/Core"
      "D:/pv/ParaView/Incubator/Core"
  )
endif()

# Import target "ParaViewIncubator::Core" for configuration "Release"
set_property(TARGET ParaViewIncubator::Core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(ParaViewIncubator::Core PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/pv/build/lib/vtkPVIncubatorCore-pv5.13.lib"
  IMPORTED_LOCATION_RELEASE "D:/pv/build/bin/vtkPVIncubatorCore-pv5.13.dll"
  )

# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "VTK::CommonCore" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()

if(DEFINED ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
  if(CMAKE_FIND_PACKAGE_NAME)
    set( ${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    set( ${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  else()
    message(FATAL_ERROR "The following imported targets are referenced, but are missing: ${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets}")
  endif()
endif()
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
