
#ifndef VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_EXPORT_H
#define VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_EXPORT_H

#ifdef VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_STATIC_DEFINE
#  define VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_EXPORT
#  define VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_NO_EXPORT
#else
#  ifndef VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_EXPORT
#    ifdef VTKExtensionsFiltersFlowPaths_EXPORTS
        /* We are building this library */
#      define VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_NO_EXPORT
#    define VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_NO_EXPORT 
#  endif
#endif

#ifndef VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_DEPRECATED
#  define VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_DEPRECATED_EXPORT
#  define VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_DEPRECATED_EXPORT VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_EXPORT VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_DEPRECATED
#endif

#ifndef VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_DEPRECATED_NO_EXPORT
#  define VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_DEPRECATED_NO_EXPORT VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_NO_EXPORT VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_DEPRECATED
#endif

/* NOLINTNEXTLINE(readability-avoid-unconditional-preprocessor-if) */
#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_NO_DEPRECATED
#    define VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkPVVTKExtensionsFiltersFlowPathsModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* VTKPVVTKEXTENSIONSFILTERSFLOWPATHS_EXPORT_H */
