# Handle the environment when running a primary step (configure, build,
# install) of a project.

set(environment "PATH;D:/pv/pvsb/install/bin;PKG_CONFIG_PATH;;PYTHONPATH;D:/pv/pvsb/install/Python/Lib/site-packages")
set(list_separator "-+-")
set(command "C:/Program Files/CMake/bin/cmake.exe;-DCMAKE_INSTALL_LIBDIR:PATH=lib;-DCMAKE_INSTALL_NAME_DIR:PATH=D:/pv/pvsb/install/lib;-DCMAKE_MACOSX_RPATH:BOOL=OFF;-DPARAVIEW_BUILD_LEGACY_REMOVE:BOOL=ON;-DPARAVIEW_BUILD_SHARED_LIBS:BOOL=ON;-DPARAVIEW_BUILD_TESTING:BOOL=OFF;-DPARAVIEW_BUILD_EDITION:STRING=CANONICAL;-DPARAVIEW_ENABLE_ADIOS2:BOOL=;-DPARAVIEW_ENABLE_ALEMBIC:BOOL=;-DPARAVIEW_ENABLE_CATALYST:BOOL=;-DPARAVIEW_ENABLE_COSMOTOOLS:BOOL=;-DPARAVIEW_ENABLE_FFMPEG:BOOL=;-DPARAVIEW_ENABLE_FIDES:BOOL=;-DPARAVIEW_ENABLE_GDAL:BOOL=;-DPARAVIEW_ENABLE_PDAL:BOOL=;-DPARAVIEW_ENABLE_LAS:BOOL=;-DPARAVIEW_ENABLE_GEOVIS:BOOL=;-DPARAVIEW_ENABLE_LOOKINGGLASS:BOOL=;-DPARAVIEW_ENABLE_MOTIONFX:BOOL=ON;-DPARAVIEW_ENABLE_OCCT:BOOL=;-DPARAVIEW_ENABLE_VISITBRIDGE:BOOL=;-DPARAVIEW_ENABLE_XDMF3:BOOL=;-DPARAVIEW_GENERATE_SPDX:BOOL=;-DPARAVIEW_INSTALL_DEVELOPMENT_FILES:BOOL=ON;-DPARAVIEW_PLUGIN_ENABLE_E57PDALReader:BOOL=FALSE;-DPARAVIEW_PLUGIN_ENABLE_GmshIO:BOOL=;-DPARAVIEW_PLUGIN_ENABLE_LookingGlass:BOOL=;-DPARAVIEW_PLUGIN_ENABLE_NodeEditor:BOOL=ON;-DPARAVIEW_PLUGIN_dsp_enable_audio_player:BOOL=;-DPARAVIEW_PLUGIN_ENABLE_XRInterface:BOOL=FALSE;-DPARAVIEW_PLUGIN_ENABLE_zSpace:BOOL=;-DPARAVIEW_XRInterface_OpenVR_Support:BOOL=;-DPARAVIEW_XRInterface_OpenXR_Support:BOOL=;-DPARAVIEW_XRInterface_OpenXRRemoting_Support:BOOL=;-DVTK_MODULE_ENABLE_VTK_RenderingOpenVR:STRING=NO;-DVTK_MODULE_ENABLE_VTK_RenderingOpenXR:STRING=NO;-DVTK_MODULE_ENABLE_VTK_RenderingOpenXRRemoting:STRING=NO;-DPARAVIEW_PLUGIN_ENABLE_NetCDFTimeAnnotationPlugin:BOOL=OFF;-DPARAVIEW_PYTHON_VERSION:STRING=3;-DPARAVIEW_USE_MPI:BOOL=;-DPARAVIEW_USE_FORTRAN:BOOL=;-DPARAVIEW_USE_PYTHON:BOOL=;-DPARAVIEW_USE_QT:BOOL=;-DVISIT_BUILD_READER_Mili:BOOL=;-DVISIT_BUILD_READER_Silo:BOOL=;-DVTK_DEFAULT_RENDER_WINDOW_OFFSCREEN:BOOL=;-DVTK_ENABLE_VR_COLLABORATION:BOOL=;-DVTK_MODULE_USE_EXTERNAL_VTK_eigen=;-DVTK_MODULE_USE_EXTERNAL_ParaView_protobuf:BOOL=;-DVTK_MODULE_USE_EXTERNAL_VTK_exodus:BOOL=;-DVTK_MODULE_USE_EXTERNAL_VTK_expat:BOOL=;-DVTK_MODULE_USE_EXTERNAL_VTK_freetype:BOOL=;-DVTK_MODULE_USE_EXTERNAL_VTK_hdf5:BOOL=;-DVTK_MODULE_USE_EXTERNAL_VTK_libproj:BOOL=;-DVTK_MODULE_USE_EXTERNAL_VTK_libxml2:BOOL=;-DVTK_MODULE_USE_EXTERNAL_VTK_mpi4py:BOOL=;-DVTK_MODULE_USE_EXTERNAL_VTK_netcdf:BOOL=;-DVTK_MODULE_USE_EXTERNAL_VTK_png:BOOL=;-DVTK_MODULE_USE_EXTERNAL_VTK_sqlite:BOOL=;-DVTK_MODULE_USE_EXTERNAL_VTK_tiff:BOOL=;-DVTK_MODULE_USE_EXTERNAL_VTK_zlib:BOOL=;-DVTK_OPENGL_HAS_EGL:BOOL=;-DVTK_OPENGL_HAS_OSMESA:BOOL=;-DVTK_SMP_IMPLEMENTATION_TYPE:STRING=Sequential;-DVTK_SMP_ENABLE_TBB:BOOL=;-DVTK_SMP_ENABLE_OPENMP:BOOL=;-DVTK_SMP_ENABLE_STDTHREAD:BOOL=ON;-DVTK_SMP_ENABLE_SEQUENTIAL:BOOL=ON;-DVTK_USE_X:BOOL=OFF;-DPARAVIEW_ENABLE_RAYTRACING:BOOL=OFF;-DVTKOSPRAY_ENABLE_DENOISER:BOOL=;-DVTK_ENABLE_OSPRAY:BOOL=;-DVTK_ENABLE_VISRTX:BOOL=;-DPARAVIEW_PLUGIN_ENABLE_pvNVIDIAIndeX:BOOL=;-DPARAVIEW_PLUGIN_ENABLE_CAVEInteraction:BOOL=ON;-DPARAVIEW_PLUGIN_CAVEInteraction_USE_VRPN:BOOL=;-DPARAVIEW_PLUGIN_ENABLE_VTKmFilters:BOOL=;-DPARAVIEW_USE_VTKM:BOOL=;-DVTK_VTKM_ENABLE_CUDA:BOOL=OFF;-DPARAVIEW_ENABLE_WEB:BOOL=;-DVTK_MODULE_ENABLE_VTK_IOSegY:STRING=YES;-DPARAVIEW_PLUGIN_ENABLE_ParFlow:BOOL=TRUE;-DPARAVIEW_ENABLE_OPENVDB:BOOL=;-DPARAVIEW_PLUGIN_ENABLE_SpaceMouseInteractor:BOOL=;-DPARAVIEW_PLUGIN_ENABLE_CDIReader:BOOL=;--no-warn-unused-cli;-DCMAKE_INSTALL_PREFIX:PATH=D:/pv/pvsb/install;-DCMAKE_PREFIX_PATH:STRING=D:/pv/pvsb/install;-DCMAKE_C_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3    ;-DCMAKE_CXX_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3 /GR /EHsc     ;-DCMAKE_Fortran_FLAGS:STRING=    ;-DCMAKE_SHARED_LINKER_FLAGS:STRING=/machine:x64    ;-DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY:BOOL=ON;-DCMAKE_C_COMPILER:STRING=C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe;-DCMAKE_CXX_COMPILER:STRING=C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe;-DCMAKE_C_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1;-DCMAKE_C_FLAGS_MINSIZEREL:STRING=/MD /O1 /Ob1 /DNDEBUG;-DCMAKE_C_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG;-DCMAKE_C_FLAGS_RELWITHDEBINFO:STRING=/MD /Zi /O2 /Ob1 /DNDEBUG;-DCMAKE_CXX_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1;-DCMAKE_CXX_FLAGS_MINSIZEREL:STRING=/MD /O1 /Ob1 /DNDEBUG;-DCMAKE_CXX_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG;-DCMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=/MD /Zi /O2 /Ob1 /DNDEBUG;-DCMAKE_BUILD_TYPE:STRING=Release;-DCMAKE_CXX_STANDARD:STRING=11;-DCMAKE_CXX_STANDARD_REQUIRED:STRING=TRUE;-Dnlohmann_json_DIR:PATH=D:/pv/pvsb/install/lib/cmake/nlohmann_json;-GNinja;D:/pv/pvsb/superbuild/paraview/src")

set(env_separator ":")
# These environment variables are prepended to using `env_separator`.
set(prepend_envvars
  PATH CMAKE_PREFIX_PATH PKG_CONFIG_PATH PYTHONPATH)
if (WIN32)
  set(env_separator ";")
elseif (APPLE)
  list(APPEND prepend_envvars
    DYLD_LIBRARY_PATH)
elseif (UNIX)
  list(APPEND prepend_envvars
    LD_LIBRARY_PATH)
endif ()

set(key)
foreach (arg IN LISTS environment)
  if (NOT key)
    set(key "${arg}")
  else ()
    list(FIND prepend_envvars "${key}" index)
    set(value "$ENV{${key}}")
    if (index EQUAL "-1" OR value STREQUAL "")
      set(value "${arg}")
    else ()
      string(PREPEND value "${arg}${env_separator}")
    endif ()
    string(REPLACE "${list_separator}" ";" value "${value}")
    set("ENV{${key}}" "${value}")

    unset(key)
  endif ()
endforeach ()

string(REPLACE "${list_separator}" "\;" command "${command}")

execute_process(
  COMMAND ${command}
  RESULT_VARIABLE rv)

if (rv)
  message(FATAL_ERROR "Failed with exit code ${rv}")
endif ()
