
#ifndef VTKPVVTKEXTENSIONSFILTERSPARALLEL_EXPORT_H
#define VTKPVVTKEXTENSIONSFILTERSPARALLEL_EXPORT_H

#ifdef VTKPVVTKEXTENSIONSFILTERSPARALLEL_STATIC_DEFINE
#  define VTKPVVTKEXTENSIONSFILTERSPARALLEL_EXPORT
#  define VTKPVVTKEXTENSIONSFILTERSPARALLEL_NO_EXPORT
#else
#  ifndef VTKPVVTKEXTENSIONSFILTERSPARALLEL_EXPORT
#    ifdef VTKExtensionsFiltersParallel_EXPORTS
        /* We are building this library */
#      define VTKPVVTKEXTENSIONSFILTERSPARALLEL_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKPVVTKEXTENSIONSFILTERSPARALLEL_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKPVVTKEXTENSIONSFILTERSPARALLEL_NO_EXPORT
#    define VTKPVVTKEXTENSIONSFILTERSPARALLEL_NO_EXPORT 
#  endif
#endif

#ifndef VTKPVVTKEXTENSIONSFILTERSPARALLEL_DEPRECATED
#  define VTKPVVTKEXTENSIONSFILTERSPARALLEL_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKPVVTKEXTENSIONSFILTERSPARALLEL_DEPRECATED_EXPORT
#  define VTKPVVTKEXTENSIONSFILTERSPARALLEL_DEPRECATED_EXPORT VTKPVVTKEXTENSIONSFILTERSPARALLEL_EXPORT VTKPVVTKEXTENSIONSFILTERSPARALLEL_DEPRECATED
#endif

#ifndef VTKPVVTKEXTENSIONSFILTERSPARALLEL_DEPRECATED_NO_EXPORT
#  define VTKPVVTKEXTENSIONSFILTERSPARALLEL_DEPRECATED_NO_EXPORT VTKPVVTKEXTENSIONSFILTERSPARALLEL_NO_EXPORT VTKPVVTKEXTENSIONSFILTERSPARALLEL_DEPRECATED
#endif

/* NOLINTNEXTLINE(readability-avoid-unconditional-preprocessor-if) */
#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKPVVTKEXTENSIONSFILTERSPARALLEL_NO_DEPRECATED
#    define VTKPVVTKEXTENSIONSFILTERSPARALLEL_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkPVVTKExtensionsFiltersParallelModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* VTKPVVTKEXTENSIONSFILTERSPARALLEL_EXPORT_H */
