
#ifndef VTKPRISMSERVERMANAGER_EXPORT_H
#define VTKPRISMSERVERMANAGER_EXPORT_H

#ifdef VTKPRISMSERVERMANAGER_STATIC_DEFINE
#  define VTKPRISMSERVERMANAGER_EXPORT
#  define VTKPRISMSERVERMANAGER_NO_EXPORT
#else
#  ifndef VTKPRISMSERVERMANAGER_EXPORT
#    ifdef vtkPrismServerManager_EXPORTS
        /* We are building this library */
#      define VTKPRISMSERVERMANAGER_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKPRISMSERVERMANAGER_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKPRISMSERVERMANAGER_NO_EXPORT
#    define VTKPRISMSERVERMANAGER_NO_EXPORT 
#  endif
#endif

#ifndef VTKPRISMSERVERMANAGER_DEPRECATED
#  define VTKPRISMSERVERMANAGER_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKPRISMSERVERMANAGER_DEPRECATED_EXPORT
#  define VTKPRISMSERVERMANAGER_DEPRECATED_EXPORT VTKPRISMSERVERMANAGER_EXPORT VTKPRISMSERVERMANAGER_DEPRECATED
#endif

#ifndef VTKPRISMSERVERMANAGER_DEPRECATED_NO_EXPORT
#  define VTKPRISMSERVERMANAGER_DEPRECATED_NO_EXPORT VTKPRISMSERVERMANAGER_NO_EXPORT VTKPRISMSERVERMANAGER_DEPRECATED
#endif

/* NOLINTNEXTLINE(readability-avoid-unconditional-preprocessor-if) */
#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKPRISMSERVERMANAGER_NO_DEPRECATED
#    define VTKPRISMSERVERMANAGER_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkPrismServerManagerModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* VTKPRISMSERVERMANAGER_EXPORT_H */
