
#ifndef VTKREMOTINGSERVERMANAGER_EXPORT_H
#define VTKREMOTINGSERVERMANAGER_EXPORT_H

#ifdef VTKREMOTINGSERVERMANAGER_STATIC_DEFINE
#  define VTKREMOTINGSERVERMANAGER_EXPORT
#  define VTKREMOTINGSERVERMANAGER_NO_EXPORT
#else
#  ifndef VTKREMOTINGSERVERMANAGER_EXPORT
#    ifdef RemotingServerManager_EXPORTS
        /* We are building this library */
#      define VTKREMOTINGSERVERMANAGER_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKREMOTINGSERVERMANAGER_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKREMOTINGSERVERMANAGER_NO_EXPORT
#    define VTKREMOTINGSERVERMANAGER_NO_EXPORT 
#  endif
#endif

#ifndef VTKREMOTINGSERVERMANAGER_DEPRECATED
#  define VTKREMOTINGSERVERMANAGER_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKREMOTINGSERVERMANAGER_DEPRECATED_EXPORT
#  define VTKREMOTINGSERVERMANAGER_DEPRECATED_EXPORT VTKREMOTINGSERVERMANAGER_EXPORT VTKREMOTINGSERVERMANAGER_DEPRECATED
#endif

#ifndef VTKREMOTINGSERVERMANAGER_DEPRECATED_NO_EXPORT
#  define VTKREMOTINGSERVERMANAGER_DEPRECATED_NO_EXPORT VTKREMOTINGSERVERMANAGER_NO_EXPORT VTKREMOTINGSERVERMANAGER_DEPRECATED
#endif

/* NOLINTNEXTLINE(readability-avoid-unconditional-preprocessor-if) */
#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKREMOTINGSERVERMANAGER_NO_DEPRECATED
#    define VTKREMOTINGSERVERMANAGER_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkRemotingServerManagerModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

/* AutoInit implementations. */
#ifdef vtkRemotingServerManager_AUTOINIT_INCLUDE
#include vtkRemotingServerManager_AUTOINIT_INCLUDE
#endif
#ifdef vtkRemotingServerManager_AUTOINIT
#include "vtkAutoInit.h"
VTK_MODULE_AUTOINIT(vtkRemotingServerManager)
#endif

#endif /* VTKREMOTINGSERVERMANAGER_EXPORT_H */
