
#ifndef VTKPVVTKEXTENSIONSFILTERSSTATISTICS_EXPORT_H
#define VTKPVVTKEXTENSIONSFILTERSSTATISTICS_EXPORT_H

#ifdef VTKPVVTKEXTENSIONSFILTERSSTATISTICS_STATIC_DEFINE
#  define VTKPVVTKEXTENSIONSFILTERSSTATISTICS_EXPORT
#  define VTKPVVTKEXTENSIONSFILTERSSTATISTICS_NO_EXPORT
#else
#  ifndef VTKPVVTKEXTENSIONSFILTERSSTATISTICS_EXPORT
#    ifdef VTKExtensionsFiltersStatistics_EXPORTS
        /* We are building this library */
#      define VTKPVVTKEXTENSIONSFILTERSSTATISTICS_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKPVVTKEXTENSIONSFILTERSSTATISTICS_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKPVVTKEXTENSIONSFILTERSSTATISTICS_NO_EXPORT
#    define VTKPVVTKEXTENSIONSFILTERSSTATISTICS_NO_EXPORT 
#  endif
#endif

#ifndef VTKPVVTKEXTENSIONSFILTERSSTATISTICS_DEPRECATED
#  define VTKPVVTKEXTENSIONSFILTERSSTATISTICS_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKPVVTKEXTENSIONSFILTERSSTATISTICS_DEPRECATED_EXPORT
#  define VTKPVVTKEXTENSIONSFILTERSSTATISTICS_DEPRECATED_EXPORT VTKPVVTKEXTENSIONSFILTERSSTATISTICS_EXPORT VTKPVVTKEXTENSIONSFILTERSSTATISTICS_DEPRECATED
#endif

#ifndef VTKPVVTKEXTENSIONSFILTERSSTATISTICS_DEPRECATED_NO_EXPORT
#  define VTKPVVTKEXTENSIONSFILTERSSTATISTICS_DEPRECATED_NO_EXPORT VTKPVVTKEXTENSIONSFILTERSSTATISTICS_NO_EXPORT VTKPVVTKEXTENSIONSFILTERSSTATISTICS_DEPRECATED
#endif

/* NOLINTNEXTLINE(readability-avoid-unconditional-preprocessor-if) */
#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKPVVTKEXTENSIONSFILTERSSTATISTICS_NO_DEPRECATED
#    define VTKPVVTKEXTENSIONSFILTERSSTATISTICS_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkPVVTKExtensionsFiltersStatisticsModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* VTKPVVTKEXTENSIONSFILTERSSTATISTICS_EXPORT_H */
