
#ifndef VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_EXPORT_H
#define VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_EXPORT_H

#ifdef VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_STATIC_DEFINE
#  define VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_EXPORT
#  define VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_NO_EXPORT
#else
#  ifndef VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_EXPORT
#    ifdef VTKExtensionsFiltersParallelDIY2_EXPORTS
        /* We are building this library */
#      define VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_NO_EXPORT
#    define VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_NO_EXPORT 
#  endif
#endif

#ifndef VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_DEPRECATED
#  define VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_DEPRECATED_EXPORT
#  define VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_DEPRECATED_EXPORT VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_EXPORT VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_DEPRECATED
#endif

#ifndef VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_DEPRECATED_NO_EXPORT
#  define VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_DEPRECATED_NO_EXPORT VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_NO_EXPORT VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_DEPRECATED
#endif

/* NOLINTNEXTLINE(readability-avoid-unconditional-preprocessor-if) */
#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_NO_DEPRECATED
#    define VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkPVVTKExtensionsFiltersParallelDIY2Module.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* VTKPVVTKEXTENSIONSFILTERSPARALLELDIY2_EXPORT_H */
