
#ifndef VTKDSPFILTERSPLUGIN_EXPORT_H
#define VTKDSPFILTERSPLUGIN_EXPORT_H

#ifdef VTKDSPFILTERSPLUGIN_STATIC_DEFINE
#  define VTKDSPFILTERSPLUGIN_EXPORT
#  define VTKDSPFILTERSPLUGIN_NO_EXPORT
#else
#  ifndef VTKDSPFILTERSPLUGIN_EXPORT
#    ifdef DSPFiltersPlugin_EXPORTS
        /* We are building this library */
#      define VTKDSPFILTERSPLUGIN_EXPORT 
#    else
        /* We are using this library */
#      define VTKDSPFILTERSPLUGIN_EXPORT 
#    endif
#  endif

#  ifndef VTKDSPFILTERSPLUGIN_NO_EXPORT
#    define VTKDSPFILTERSPLUGIN_NO_EXPORT 
#  endif
#endif

#ifndef VTKDSPFILTERSPLUGIN_DEPRECATED
#  define VTKDSPFILTERSPLUGIN_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKDSPFILTERSPLUGIN_DEPRECATED_EXPORT
#  define VTKDSPFILTERSPLUGIN_DEPRECATED_EXPORT VTKDSPFILTERSPLUGIN_EXPORT VTKDSPFILTERSPLUGIN_DEPRECATED
#endif

#ifndef VTKDSPFILTERSPLUGIN_DEPRECATED_NO_EXPORT
#  define VTKDSPFILTERSPLUGIN_DEPRECATED_NO_EXPORT VTKDSPFILTERSPLUGIN_NO_EXPORT VTKDSPFILTERSPLUGIN_DEPRECATED
#endif

/* NOLINTNEXTLINE(readability-avoid-unconditional-preprocessor-if) */
#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKDSPFILTERSPLUGIN_NO_DEPRECATED
#    define VTKDSPFILTERSPLUGIN_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkDSPFiltersPluginModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* VTKDSPFILTERSPLUGIN_EXPORT_H */
