
#ifndef VTKPVVTKEXTENSIONSIOIMPORT_EXPORT_H
#define VTKPVVTKEXTENSIONSIOIMPORT_EXPORT_H

#ifdef VTKPVVTKEXTENSIONSIOIMPORT_STATIC_DEFINE
#  define VTKPVVTKEXTENSIONSIOIMPORT_EXPORT
#  define VTKPVVTKEXTENSIONSIOIMPORT_NO_EXPORT
#else
#  ifndef VTKPVVTKEXTENSIONSIOIMPORT_EXPORT
#    ifdef VTKExtensionsIOImport_EXPORTS
        /* We are building this library */
#      define VTKPVVTKEXTENSIONSIOIMPORT_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKPVVTKEXTENSIONSIOIMPORT_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKPVVTKEXTENSIONSIOIMPORT_NO_EXPORT
#    define VTKPVVTKEXTENSIONSIOIMPORT_NO_EXPORT 
#  endif
#endif

#ifndef VTKPVVTKEXTENSIONSIOIMPORT_DEPRECATED
#  define VTKPVVTKEXTENSIONSIOIMPORT_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKPVVTKEXTENSIONSIOIMPORT_DEPRECATED_EXPORT
#  define VTKPVVTKEXTENSIONSIOIMPORT_DEPRECATED_EXPORT VTKPVVTKEXTENSIONSIOIMPORT_EXPORT VTKPVVTKEXTENSIONSIOIMPORT_DEPRECATED
#endif

#ifndef VTKPVVTKEXTENSIONSIOIMPORT_DEPRECATED_NO_EXPORT
#  define VTKPVVTKEXTENSIONSIOIMPORT_DEPRECATED_NO_EXPORT VTKPVVTKEXTENSIONSIOIMPORT_NO_EXPORT VTKPVVTKEXTENSIONSIOIMPORT_DEPRECATED
#endif

/* NOLINTNEXTLINE(readability-avoid-unconditional-preprocessor-if) */
#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKPVVTKEXTENSIONSIOIMPORT_NO_DEPRECATED
#    define VTKPVVTKEXTENSIONSIOIMPORT_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkPVVTKExtensionsIOImportModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* VTKPVVTKEXTENSIONSIOIMPORT_EXPORT_H */
