
#ifndef VTKCONTOURLABELPLUGIN_EXPORT_H
#define VTKCONTOURLABELPLUGIN_EXPORT_H

#ifdef VTKCONTOURLABELPLUGIN_STATIC_DEFINE
#  define VTKCONTOURLABELPLUGIN_EXPORT
#  define VTKCONTOURLABELPLUGIN_NO_EXPORT
#else
#  ifndef VTKCONTOURLABELPLUGIN_EXPORT
#    ifdef ContourLabelRepresentation_EXPORTS
        /* We are building this library */
#      define VTKCONTOURLABELPLUGIN_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKCONTOURLABELPLUGIN_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKCONTOURLABELPLUGIN_NO_EXPORT
#    define VTKCONTOURLABELPLUGIN_NO_EXPORT 
#  endif
#endif

#ifndef VTKCONTOURLABELPLUGIN_DEPRECATED
#  define VTKCONTOURLABELPLUGIN_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKCONTOURLABELPLUGIN_DEPRECATED_EXPORT
#  define VTKCONTOURLABELPLUGIN_DEPRECATED_EXPORT VTKCONTOURLABELPLUGIN_EXPORT VTKCONTOURLABELPLUGIN_DEPRECATED
#endif

#ifndef VTKCONTOURLABELPLUGIN_DEPRECATED_NO_EXPORT
#  define VTKCONTOURLABELPLUGIN_DEPRECATED_NO_EXPORT VTKCONTOURLABELPLUGIN_NO_EXPORT VTKCONTOURLABELPLUGIN_DEPRECATED
#endif

/* NOLINTNEXTLINE(readability-avoid-unconditional-preprocessor-if) */
#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKCONTOURLABELPLUGIN_NO_DEPRECATED
#    define VTKCONTOURLABELPLUGIN_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkContourLabelPluginModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* VTKCONTOURLABELPLUGIN_EXPORT_H */
