
#ifndef VTKGEODESICMEASUREMENTFILTERS_EXPORT_H
#define VTKGEODESICMEASUREMENTFILTERS_EXPORT_H

#ifdef VTKGEODESICMEASUREMENTFILTERS_STATIC_DEFINE
#  define VTKGEODESICMEASUREMENTFILTERS_EXPORT
#  define VTKGEODESICMEASUREMENTFILTERS_NO_EXPORT
#else
#  ifndef VTKGEODESICMEASUREMENTFILTERS_EXPORT
#    ifdef GeodesicMeasurementFilters_EXPORTS
        /* We are building this library */
#      define VTKGEODESICMEASUREMENTFILTERS_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKGEODESICMEASUREMENTFILTERS_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKGEODESICMEASUREMENTFILTERS_NO_EXPORT
#    define VTKGEODESICMEASUREMENTFILTERS_NO_EXPORT 
#  endif
#endif

#ifndef VTKGEODESICMEASUREMENTFILTERS_DEPRECATED
#  define VTKGEODESICMEASUREMENTFILTERS_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKGEODESICMEASUREMENTFILTERS_DEPRECATED_EXPORT
#  define VTKGEODESICMEASUREMENTFILTERS_DEPRECATED_EXPORT VTKGEODESICMEASUREMENTFILTERS_EXPORT VTKGEODESICMEASUREMENTFILTERS_DEPRECATED
#endif

#ifndef VTKGEODESICMEASUREMENTFILTERS_DEPRECATED_NO_EXPORT
#  define VTKGEODESICMEASUREMENTFILTERS_DEPRECATED_NO_EXPORT VTKGEODESICMEASUREMENTFILTERS_NO_EXPORT VTKGEODESICMEASUREMENTFILTERS_DEPRECATED
#endif

/* NOLINTNEXTLINE(readability-avoid-unconditional-preprocessor-if) */
#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKGEODESICMEASUREMENTFILTERS_NO_DEPRECATED
#    define VTKGEODESICMEASUREMENTFILTERS_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkGeodesicMeasurementFiltersModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* VTKGEODESICMEASUREMENTFILTERS_EXPORT_H */
