
#ifndef LEGACYGHOSTCELLSGENERATORFILTERS_EXPORT_H
#define LEGACYGHOSTCELLSGENERATORFILTERS_EXPORT_H

#ifdef LEGACYGHOSTCELLSGENERATORFILTERS_STATIC_DEFINE
#  define LEGACYGHOSTCELLSGENERATORFILTERS_EXPORT
#  define LEGACYGHOSTCELLSGENERATORFILTERS_NO_EXPORT
#else
#  ifndef LEGACYGHOSTCELLSGENERATORFILTERS_EXPORT
#    ifdef LegacyGhostCellsGeneratorFilters_EXPORTS
        /* We are building this library */
#      define LEGACYGHOSTCELLSGENERATORFILTERS_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define LEGACYGHOSTCELLSGENERATORFILTERS_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef LEGACYGHOSTCELLSGENERATORFILTERS_NO_EXPORT
#    define LEGACYGHOSTCELLSGENERATORFILTERS_NO_EXPORT 
#  endif
#endif

#ifndef LEGACYGHOSTCELLSGENERATORFILTERS_DEPRECATED
#  define LEGACYGHOSTCELLSGENERATORFILTERS_DEPRECATED __declspec(deprecated)
#endif

#ifndef LEGACYGHOSTCELLSGENERATORFILTERS_DEPRECATED_EXPORT
#  define LEGACYGHOSTCELLSGENERATORFILTERS_DEPRECATED_EXPORT LEGACYGHOSTCELLSGENERATORFILTERS_EXPORT LEGACYGHOSTCELLSGENERATORFILTERS_DEPRECATED
#endif

#ifndef LEGACYGHOSTCELLSGENERATORFILTERS_DEPRECATED_NO_EXPORT
#  define LEGACYGHOSTCELLSGENERATORFILTERS_DEPRECATED_NO_EXPORT LEGACYGHOSTCELLSGENERATORFILTERS_NO_EXPORT LEGACYGHOSTCELLSGENERATORFILTERS_DEPRECATED
#endif

/* NOLINTNEXTLINE(readability-avoid-unconditional-preprocessor-if) */
#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef LEGACYGHOSTCELLSGENERATORFILTERS_NO_DEPRECATED
#    define LEGACYGHOSTCELLSGENERATORFILTERS_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: LegacyGhostCellsGeneratorFiltersModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

/* AutoInit implementations. */
#ifdef LegacyGhostCellsGeneratorFilters_AUTOINIT_INCLUDE
#include LegacyGhostCellsGeneratorFilters_AUTOINIT_INCLUDE
#endif
#ifdef LegacyGhostCellsGeneratorFilters_AUTOINIT
#include "vtkAutoInit.h"
VTK_MODULE_AUTOINIT(LegacyGhostCellsGeneratorFilters)
#endif

#endif /* LEGACYGHOSTCELLSGENERATORFILTERS_EXPORT_H */
