
#ifndef VTKBIVARIATEREPRESENTATIONS_EXPORT_H
#define VTKBIVARIATEREPRESENTATIONS_EXPORT_H

#ifdef VTKBIVARIATEREPRESENTATIONS_STATIC_DEFINE
#  define VTKBIVARIATEREPRESENTATIONS_EXPORT
#  define VTKBIVARIATEREPRESENTATIONS_NO_EXPORT
#else
#  ifndef VTKBIVARIATEREPRESENTATIONS_EXPORT
#    ifdef vtkBivariateRepresentations_EXPORTS
        /* We are building this library */
#      define VTKBIVARIATEREPRESENTATIONS_EXPORT 
#    else
        /* We are using this library */
#      define VTKBIVARIATEREPRESENTATIONS_EXPORT 
#    endif
#  endif

#  ifndef VTKBIVARIATEREPRESENTATIONS_NO_EXPORT
#    define VTKBIVARIATEREPRESENTATIONS_NO_EXPORT 
#  endif
#endif

#ifndef VTKBIVARIATEREPRESENTATIONS_DEPRECATED
#  define VTKBIVARIATEREPRESENTATIONS_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKBIVARIATEREPRESENTATIONS_DEPRECATED_EXPORT
#  define VTKBIVARIATEREPRESENTATIONS_DEPRECATED_EXPORT VTKBIVARIATEREPRESENTATIONS_EXPORT VTKBIVARIATEREPRESENTATIONS_DEPRECATED
#endif

#ifndef VTKBIVARIATEREPRESENTATIONS_DEPRECATED_NO_EXPORT
#  define VTKBIVARIATEREPRESENTATIONS_DEPRECATED_NO_EXPORT VTKBIVARIATEREPRESENTATIONS_NO_EXPORT VTKBIVARIATEREPRESENTATIONS_DEPRECATED
#endif

/* NOLINTNEXTLINE(readability-avoid-unconditional-preprocessor-if) */
#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKBIVARIATEREPRESENTATIONS_NO_DEPRECATED
#    define VTKBIVARIATEREPRESENTATIONS_NO_DEPRECATED
#  endif
#endif

/* VTK-HeaderTest-Exclude: vtkBivariateRepresentationsModule.h */

/* Include ABI Namespace */
#include "vtkABINamespace.h"

#endif /* VTKBIVARIATEREPRESENTATIONS_EXPORT_H */
